name: ${project.name}
main: lol.suicide.uber.Uber
author: suicide#0001
version: ${project.version}
description: ${project.description}
website: ${project.url}
api-version: 8

commands:
  ride:
    usage: /<command>
    description: Ride the entity that you are looking at.